baseURL = "https://example.com"
languageCode = "en-us"
title = "Some Title"
theme = "bare-hugo-theme"
enableGitInfo = true

[taxonomies]
  tag = "tags"
  series = "series"

[params]
mainSections = ["posts"]
author = "Joe Bloggs"
email = "hello@hello-world.com"
repoLink = "https://github.com/orf/hugo-bare-theme"
description = 'Something about myself'
postcss = true

[[params.social]]
icon = "github-circle"
url = "https://github.com/orf/"